start clocher_out/clocher_out.toe
timeout 1
start clocher/Fond/fond.toe
timeout 1
start clocher/Clocher_transitions.toe
timeout 1
start clocher/master_clocher.toe
timeout 1
start Rectorat/rectorat.toe