start clocher_out/clocher_out.toe
timeout 1
start clocher_fond/clocher_fond.toe
timeout 1
start clocher_front/clocher_front.toe
timeout 1
start clocher_master/clocher_master.toe
timeout 1
start rectorat/rectorat.toe
timeout 1
start rectorat_out/rectorat_out.toe