start master/master.toe
timeout 2
start master/masterLedsOutVeines.toe
timeout 2
start master/masterLedsOut_Plafond.toe
timeout 2
start master_in/master_inA.toe
timeout 2
start master_in/master_inB.toe
timeout 2
start master_dmx/master_dmx_foret.toe
timeout 2
start master_dmx/master_dmx_pp.toe
timeout 2
start arbres_master/arbres_master.toe
timeout 2
start arbres_A/arbres_A.toe
timeout 2
start arbres_B/arbres_B.toe
timeout 2
start lanternes/lanternes.toe
timeout 2
start etang/etang.toe
timeout 2
start saules/saules.toe
