start master/master.toe
timeout 1
start master_in/master_in.toe
timeout 1
start arbres_master/arbres_master.toe
timeout 1
start arbres_A/arbres_A.toe
timeout 1
start arbres_B/arbres_B.toe
timeout 1
start lanternes/lanternes.toe
timeout 1
start riviere/riviere.toe
timeout 1
start saules/saules.toe
